# Generated by Django 6.0.1 on 2026-02-09 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('account_type', models.CharField(choices=[('checking', 'Conta Corrente'), ('savings', 'Poupança'), ('investment', 'Investimento'), ('cash', 'Dinheiro'), ('other', 'Outro')], max_length=20, verbose_name='tipo de conta')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo')),
                ('color', models.CharField(default='#06b6d4', help_text='Cor em formato hexadecimal (ex: #06b6d4)', max_length=7, verbose_name='cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['name'],
            },
        ),
    ]
