# Generated by Django 6.0.1 on 2026-02-09 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('category_type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='tipo')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone (ex: home, car, food)', max_length=50, verbose_name='ícone')),
                ('color', models.CharField(default='#06b6d4', help_text='Cor em formato hexadecimal (ex: #06b6d4)', max_length=7, verbose_name='cor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['category_type', 'name'],
            },
        ),
    ]
